version: '3.8'
services:
  redis-stack:
    container_name: redis-stack
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'

  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data_container:/data/db'

volumes:
  mongodb_data_container:
